#!/bin/bash
set -e

exec >> /var/log/bluetooth-handler.log
exec 2>&1

echo "## bluetooth-handler $1 $2"

if [ "$1" = "add" ]; then
  DEVICE_ID=`cat /sys/devices/virtual/input/input$2/name`
  DEVICE_ID=`echo "$DEVICE_ID" | sed -e 's/ (AVRCP)//'`
  echo "$DEVICE_ID" > /var/bluetooth-handler-input$2
  echo "Device ID: $DEVICE_ID"

  sudo -H -u pi XDG_RUNTIME_DIR=/run/user/1000 /usr/bin/speech.sh "Connected to $DEVICE_ID"

  # turn off BT discover mode
  bluetoothctl discoverable off
fi

if [ "$1" = "remove" ]; then
  DEVICE_ID=`cat /var/bluetooth-handler-input$2`
  rm /var/bluetooth-handler-input$2
  echo "Device ID: $DEVICE_ID"

  sudo -H -u pi XDG_RUNTIME_DIR=/run/user/1000 /usr/bin/speech.sh "$DEVICE_ID disconnected"

  # turn on bluetooth discovery if device disconnects
  bluetoothctl discoverable on
fi
